name: Daily Minefort Keep-Alive and Backup

on:
  schedule:
    # Run every day at 03:00 UTC (adjust time as needed)
    # Use a tool like crontab.guru to pick your desired UTC time
    - cron: '0 3 * * *'
  workflow_dispatch:
    # Allows you to manually trigger the workflow from the Actions tab

jobs:
  automate:
    runs-on: ubuntu-latest # Use a standard Ubuntu runner provided by GitHub

    permissions: # <--- CORRECT LOCATION: This is at the job level
      contents: write # Grant write permissions to the GITHUB_TOKEN for cloning/pushing

    steps: # <--- Steps start here, after permissions

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Use a recent stable Node.js version

    - name: Install Node.js dependencies
      run: npm install
      working-directory: . # Assumes package.json is at the repo root

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use a recent Python 3 version

    # Note: ftplib is a built-in Python library, no need to install from requirements.txt
    # If you need other libs later, uncomment and add them to requirements.txt
    # - name: Install Python dependencies
    #   run: pip install -r requirements.txt
    #   working-directory: .


    - name: Run Mineflayer Bot to Start Server and Wait for Join
      # This step will only succeed (exit 0) if the bot successfully joins the target server world
      # If it fails (e.g., login failed, command failed, timeout), it will exit non-zero
      run: node src/start_bot.js
      env:
        MINEFORT_EMAIL: ${{ secrets.MINEFORT_EMAIL }}
        MINEFORT_PASSWORD: ${{ secrets.MINEFORT_PASSWORD }}
        MINEFORT_SERVER_NAME: ${{ secrets.MINEFORT_SERVER_NAME }} # Should be 'ForAboniii'
      # If this step fails, the subsequent steps will be skipped (default behavior)
      # continue-on-error: false # This is the default, making it explicit here

    - name: Run Backup and Upload Script
      # This step will only run if the previous 'Run Mineflayer Bot' step succeeded
      run: python src/backup_and_upload.py
      env:
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        BACKUP_REPO_URL: ${{ secrets.BACKUP_REPO_URL }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use the default GITHUB_TOKEN secret
      # permissions is NOT needed here, it's at the job level
